CREATE TABLE IF NOT EXISTS justin_dtglvl2dbassessment2021.products(
  title               VARCHAR(60) NOT NULL
  ,series              VARCHAR(60) NOT NULL
  ,price               NUMERIC(6,2) NOT NULL
  ,sku                 VARCHAR(30) NOT NULL
  ,description         VARCHAR(1400) NOT NULL
  ,date                DATE  NOT NULL
  ,volume              SMALLINT 
  ,number              SMALLINT 
  ,category            VARCHAR(20) NOT NULL
  ,image               VARCHAR(30) NOT NULL
  ,publisher           INTEGER NOT NULL
  ,PRIMARY KEY (sku)
  ,FOREIGN KEY (publisher) REFERENCES justin_dtglvl2dbassessment2021.manufacturers(publisher)
);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Shades of Grey','X-Man',6.00,'75960604204301911','Shades of Grey  - Nate breaks Sinister’s control and leaves to confront Onslaught. NB: This item is in a used condition.','1996-09-01',1,19,'comics','75960604204301911.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('X-Factor','X-Factor',6.00,'7148603283002','NB: This item is in a used condition.','2008-02-01',NULL,26,'comics','7148603283002.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('X-Man','X-Man',6.00,'75960604204302311','NB: This item is in a used condition.','1996-11-08',NULL,23,'comics','75960604204302311.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Common Ground','X-Man ’97',6.00,'75960604469600111','Nate finds himself allied with his greatest enemies to escape the clutches of the Shi’ar. NB: This item is in a used condition.','1998-02-01',NULL,1,'comics','75960604469600111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('X-Man','X-Man',5.00,'72527403283907','NB: This item is in a used condition.','1997-07-01',1,1,'comics','72527403283907.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Hunted Below','X-Man',6.00,'75960604204301311','X-Man saves Threnody from the Marauders. NB: This item is in a used condition.','1996-03-01',1,13,'comics','75960604204301311.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('In the Company of Strangers','X-Man',5.00,'75960604204301811','Mr. Sinister and the Marauders hunt down Threnody. X-Force tries to protect Nate from Onslaught but end up losing him to Sinister. NB: This item is in a used condition.','1996-08-01',1,18,'comics','75960604204301811.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('X-Factor','X-Factor',7.00,'75960605729000111','Written by PETER DAVID Pencils & Cover by RYAN SOOK In the fallout from HOUSE OF M and following last year’s surprise hit film-noir series–MADROX, a new mutant team is forged! X-FACTOR is an investigative mutant agency including Madrox-the Multiple Man, Guido-the Strong Guy, Wolfsbane-the shape-shifter, Siryn-the chorus girl, Rictor-the living earthquake, and GENERATION X’s Monet-the pompous witch. Drawn together in the heart of District X, this rag-tag band of heroes has a lot of answers to find, and fast! BONUS: A key player from HOUSE OF M will play a major roll in X-FACTOR! (No, it’s not Wolverine-sigh)','2006-01-01',NULL,1,'comics','75960605729000111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('X-Factor','X-Factor',6.00,'75960602145110621','NB: This item is in a used condition.','2008-09-01',NULL,106,'comics','75960602145110622.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('X-Factor','X-factor',7.00,'75960605878501211','Written by PETER DAVID Penciled by RENATO ARLEM Cover by RYAN SOOK It all climaxes here: The final showdown with Mr. Tryp and Singularity, X-Factor’s desperate race to save all the former mutants from annihilation, and the truth behind the shocking traitor in their midst. 32 PGS./Rated T+ …$2.99 NB: This item is in a used condition.','2006-06-03',NULL,12,'comics','75960605878501211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Strip Search','X-Factor',8.00,'75960605878520911','Written by PETER DAVID Penciled by EMANUELA LUPACCHINO Cover by DAVID YARDIN It may happen in Vegas, but it''s very likely not going to stay there as X-Factor in general – and Longshot in particular – are unleashed on the Las Vegas strip, determined to face down the goddess of death in her lair and save a very unusual client… 32 PGS./Rated T+ …$2.99','2010-11-01',NULL,209,'comics','75960605878520911.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Isolationist, Conclusion','X-Factor',7.00,'75960605878502411','The stunning conclusion to THE ISOLATIONIST. Josef Huber has been manipulating X-Factor in the hopes of gathering together all mutants. But post M-Day, with their numbers dwindling, amassing the world’s remaining mutants could reduce them to a single target. With Layla Miller lost and wandering the streets of New York, Siryn and Monet shepherding the twins Molly and Wally to safety, and the rest of the team still reeling from their confrontation with Quicksilver, can X-Factor Investigations uncover Huber’s plans before harm comes to the remnants of mutantkind? [per solicitation]','2007-12-01',NULL,24,'comics','75960605878502411.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('All-New X-Men','All-New X-Men',8.50,'75960608342801011','“APOCALYPSE WARS” CONTINUES! • The ALL-NEW X-MEN are on a mission to write their own futures…and none is more determined to escape their destiny than Evan Sabahnur, who is to one day become the next host for the genocidal villain APOCALYPSE. • But now, by way of unintentional intervention by his teammate Beast, Evan finds himself thousands of years in the past, in Egypt…and on the run alongside his predecessor, En Sabah Nur, the boy who will one day become Apocalypse himself! • To change his future, will Evan literally change the course of history? • Or will he instead be Apocalypse''s first victim?? Rated T+','2016-08-01',NULL,10,'comics','75960608342801011.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('All-New X-Men','All-New X-Men',8.50,'75960608342801111','“APOCALYPSE WARS” CONCLUSION! • Destined to one day become the next host of the genocidal villain Apocalypse, Evan Sabahnur is determined to change his fate. • And now, thousands years in the past, in Ancient Egypt, Evan has allied himself with En Sabah Nur, the boy who will one day become Apocalypse himself! • But will the lessons Evan learns in the past seal his fate…or enable him to avert it? Rated T+','2016-09-01',NULL,11,'comics','75960608342801111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('All-New X-Men vs Uncanny Avengers','All-New X-Men',8.50,'75960607900101211','The All-New X-Men find themselves face-to-face with the UNCANNY AVENGERS!  Young Cyclops meets the adult version of the little brother he thought he may never see again.','2013-08-01',NULL,12,'comics','75960607900101211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('All-New X-Men','All-New X-Men',8.50,'75960607900101311','The All-New X-Men find themselves face-to-face with the UNCANNY AVENGERS! • Young Cyclops meets the adult version of the little brother he thought he may never see again.','2013-08-01',NULL,13,'comics','75960607900101311.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('All-New X-Men','All-New X-Men',8.50,'75960608342801411','A wheelchair-bound CYCLOPS is stuck in the X-Men''s mobile headquarters while all of his teammates jet off across the world on fantastic adventures. • Well, almost all of his teammates…BEAST has sequestered himself in his lab, feverishly working on some mysterious new project. • In his own version of Rear Window, will Cyclops discover that Hank is meddling with forces that should be left alone, or is he just driving himself mad out of boredom? Or worse – BOTH? Rated T+','2016-12-01',NULL,14,'comics','75960608342801411.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('All-New X-Men','All-New X-Men',8.50,'75960608342801511','The All-New X-Men have been keeping secrets from one another… • But when the GOBLIN QUEEN comes calling, they''ll have to confront their demons…LITERALLY! Rated T+','2017-01-01',NULL,15,'comics','75960608342801511.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Avengers','Avengers',8.50,'75960608603001011','SECRET EMPIRE TIE-IN! • They’re Earth’s Mightiest – but are they heroes? Taskmaster, Deadpool, the Superior Octopus…how can they be fighting alongside the Avengers we know? Rated T+','2013-08-01',NULL,10,'comics','75960608603001011.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('To the End','Avengers',5.00,'75960607902501611','“THE TWO WORLDS SOLUTION” • Prelude to INFINITY: Part Three. • The battle between the Avengers and Mad Earth heats up. • Whatever happened to Ex Nihilo and Abyss, and for that matter, Starbrand and Nightmask as well?','2013-09-01',NULL,16,'comics','75960607902501611.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Avengers','Avengers',9.00,'75960608603000211','KANG WAR TWO! The Vision is hell-bent on revenge against Kang and if the Avengers can''t hold the synthezoid back, all of history is in jeopardy! Rated T+','2017-02-01',NULL,2,'comics','75960608603000211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Gods and Soldiers','Avengers',8.00,'75960607902502711','“ADAPT OR DIE” • The secret behind the All-New Avengers revealed! • The science war overtakes the world(s). • All the answers to the questions you wished remained hidden. • The collision of Avengers and New Avengers is imminent.','2014-05-01',NULL,27,'comics','75960607902502711.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Last Avenger','Avengers',8.50,'75960607902503411','ORIGINAL SIN tie-in! – “THIS PROBLEM OF AVENGERS” • The first Avenger meets the last Avenger… • And the Avengers World crumbles. • You won''t believe what comes next.','2014-10-01',NULL,34,'comics','75960607902503411.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Moon River','Aquaman',5.00,'76194123532501011','Written by Rick Veitch; ART by Yvel Guichet and Mark Propst; COVER by Andrew Robinson In stores September 10. Black Manta and Aquaman travel to Dreamtime to battle the Thirst for the soul of the fourth and final river goddess! Meanwhile, Tempest is back in Atlantis, where he discovers a monstrosity pumping dark, satanic energy into the oceans. FC, 32 pg','2003-11-01',NULL,10,'comics','76194123532501011.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('By the Rivers of Babylon!','Aquaman',5.00,'76194123532501111','Written by Rick Veitch; ART by Yvel Guichet and Mark Propst; COVER by Tony Harris In stores October 15. Aquaman rushes towards a climactic battle with his deadliest enemy, the Thirst, at the mythical Fountainhead – the source of the four rivers that bring all spiritual energy into our world. But even with his Black Manta at his side, nothing can stop Aquman from meeting an unexpected fate that will leave him reeling! FC, 32 pg','2003-12-01',NULL,11,'comics','76194123532501111.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Deluge Act One','Aquaman',8.50,'76194134183501211','“THE DELUGE” part one! It''s war! With the undersea army of N.E.M.O. at his command, Black Manta draws the U.S. and Atlantis into the war Aquaman has been fighting to prevent. Now the sea king races to uncover proof of N.E.M.O.''s deception before the two nations destroy each other.','2017-02-01',NULL,12,'comics','76194134183501211.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Colombian Connection','Bullseye',5.00,'75960608591000211','MONEY, TORTURE, MURDER! • Rescuing a mobster''s son from a drug cartel isn''t easy…Bullseye just makes it look that way! Rated T+','2017-05-01',NULL,2,'comics','75960608591000211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Hunted','Black Panther',8.00,'75960603876300611','The Black Panther is ambushed by Kraven following a state dinner in New York.','1999-03-01',2,6,'comics','75960603876300611.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Superheavy Part One','Batman',5.00,'76194130640704111','The all-new Batman makes his debut! Who is he, and what happens next? Find out here as a new era begins in Gotham City!','2015-08-01',NULL,41,'comics','76194130640704111.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Superheavy Part Five','Batman',8.50,'76194130640704511','When Batman almost gets taken out by a new threat, Jim Gordon might have to reevaluate what it means to wear the cowl before it''s too late for Gotham City!','2015-12-01',NULL,45,'comics','76194130640704511.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Captain Marvel','Captain Marvel',5.00,'75960604815100221','NB: This item is in a used condition','1996-01-12',NULL,2,'comics','75960604815100221.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Junior Achievement','Captain Marvel',6.00,'75960604284500111','Did the son of Captain Mar-vell kill 2,000 people, or was he framed for murder?','1995-12-01',1,1,'comics','75960604284500111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Power of Strange Compels You','Doctor Strange',5.00,'75960608301501911','Mister Misery has kidnapped Wong and is using everything Strange''s friend and companion knows about the Sorcerer Supreme. • A compromised Strange must find a way to defeat the sadistic entity without killing Wong! Rated T+','2017-06-01',NULL,19,'comics','75960608301501911.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Doctor Strange','Doctor Strange',5.00,'75960608301502111','Doctor Strange must free New York City from the Darkforce dome that envelops it.','2017-07-01',NULL,21,'comics','75960608301502111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Defenders','The Defenders',15.50,'7148602152011','NB: This item is in a used condition.','1985-11-01',NULL,41,'comics','7148602152011.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Defenders','The Defenders',15.50,'7148602152005','NB: This item is in a used condition.','1986-01-11',NULL,59,'comics','7148602152005.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Love is Blind','Elektra',10.00,'75960604360699911','Elektra seeks revenge for the murder of her father and meets Stick.','1997-07-01',1,1,'comics','75960604360699911.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Self-Evident Truths!','Fantastic Four',8.00,'75960607906301011','BEN FRANKLIN WAS A SKRULL!','2013-09-01',NULL,10,'comics','75960607906301011.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Race against Time, Finish Line: Double Team','Flash',8.00,'76194120024811711','Together, Wally West and John Fox defeat Dr. Polaris’ and Abra Kadabra’s plans for a new ice age and free Iris, though Polaris is able to flee. However, Linda remains frozen and the authorities from his time period have come for John Fox in the form of Speed Metal.','1996-09-01',NULL,117,'comics','76194120024811711.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Death at the Top of the World, Part 3','Flash',8.00,'76194120024813511','NB: This item is in a used condition.','1998-03-01',NULL,135,'comics','76194120024813511.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Friends and Foes','Groo',8.50,'76156827698500111','Each month of this yearlong series, Groo and his faithful pooch, Rufferto, encounter a different acquaintance–or enemy–with the usual dire consequences! In #1, Groo crosses paths with Captain Ahax, the seaman with the world record for most ships sunk by the all-time stupidest character in comics! Brought to you by the award-winning team of Sergio Aragonés and Mark Evanier!','2015-01-01',NULL,1,'comics','76156827698500111.jpg',4);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Friends and Foes','Groo',8.50,'76156827698500211','The Year of Groo continues! As Groo roams from town to town, wreaking his usual havoc, he runs into his beloved Granny Groo, who raised him from an inept young toddler to an even less-ept older idiot. Can she use Groo in a profitable scheme? Well, what do you think? From Sergio Aragonés and Mark Evanier, with Stan Sakai and Tom Luth!','2015-02-01',NULL,2,'comics','76156827698500211.jpg',4);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Play of the Gods','Groo',5.00,'76156800184600411','Groo finds himself the unwitting pawn in a game that involves a newly-found land filled with gold. There are those who think, “How do we convert their gold to our gold?” and also “How do we convert their gods to our gods?” How does Groo figure into all of this and, more important, how does he create doom and destruction for all? It''s brought to you (as usual) by the award-winning team of Sergio Aragonés and Mark Evanier, with the help of Stan Sakai and Tom Luth. o Eisner and Harvey Award-winning creators, and an Eisner Award-winning title!','2017-10-01',NULL,4,'comics','76156800184600411.jpg',4);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Takeout from Tuliebitz’s','Guardians of Infinity',5.00,'75960608396100411','AN ALL-NEW, ALL-DIFFERENT GOD ARISES! • This is the dawning of the age of Hermetikus! He''s the Lord of the Newcomers and seems to have access to all of space and time! • And he also seems to have complicated history with Stella Nega, leader of the Guardians 1000! • Plus, GERRY DUGGAN and RAFA GARRES bring you a rollicking tale of space brawlin'' with VENOM and THE HUMAN TORCH! Rated T','2016-05-01',NULL,4,'comics','75960608396100411.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Guardians of Knowhere','Guardians of Knowhere',8.50,'75960608285800211','SECRET WARS SERIES • In a colony of thugs and criminals, there''s plenty of work in maintaining the “peace” of Knowhere • But a new power is rising, one that threatens to tear apart the threadbare fabric of the celestial head''s society. • The mantle of a Guardian weighs heavily on its bearers shoulders. • Will those destined to safeguard Battleworld''s moon accept that burden in time to save its citizens? Rated T','2015-10-01',NULL,2,'comics','75960608285800211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Guardians of the Galaxy','Guardians of the Galaxy',5.00,'75960607830101211','The Guardians team up with members of the X-Men as, on the Shi’ar homeworld, the trial of Jean Grey begins.','2014-04-01',NULL,12,'comics','75960607830101211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Guarding the Globe','Guarding the Globe',8.50,'70985300886600111','After Robot and Monster Girl are trapped in another dimension, Cecil and Donald begin a major recruiting drive for the team. Elsewhere, Set is beginning a recruitment drive of his own, finding super-villains for The Order.','2010-08-01',NULL,1,'comics','70985300886600111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('No Exit','Hulk 2099',10.00,'75960602288500111','Hulk 2099 battles Draco over a water reclamation facility illegally built on land that’s being inhabited by people that were displaced by the cataclysm, who will be the victor?','1994-12-01',1,1,'comics','75960602288500111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Powers and Abilities [Part One]','H-E-R-O',3.00,'76194123375800111','The mysterious H-E-R-O device grants super-powers to its bearer, but how will each handle those powers?','2003-04-01',NULL,1,'comics','76194123375800111.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Great Leap Forward','H-E-R-O',3.00,'76194123375801111','A neanderthal man finds the H-E-R-O Dial and, with his super-powers, roams the world, perhaps causing several pregnancies and creating an evolutionary leap while super-powered. He sketches his discoveries in a cave at the site of present day Metropolis and, as his last journey, he visits the moon and dies there.','2004-02-01',NULL,11,'comics','76194123375801111.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Girl Power','H-E-R-O',3.00,'76194123375800611','Andrea Allen shares the H-E-R-O dial with two new friends and they all get in trouble with their school principal until she finds a way to explain away the superheroes. But she then loses the H-E-R-O dial from a moving car in a struggle with one of her friends.','2003-09-01',NULL,6,'comics','76194123375800611.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Hercules Fall Of An Avenger','Hercules Fall Of An Avenger',5.00,'75960607093000111','When the most beloved Olympian of all time falls, who will mourn him?','2009-01-01',NULL,1,'comics','75960607093000111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Iceman','Iceman',5.00,'75960608653500111','Between dealing with the time-displaced younger version of himself, his non-existent love-life, and saving young mutants from angry, homicidal Purifiers, it’s not easy being Iceman.','2017-08-01',NULL,1,'comics','75960608653500111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Iceman','Iceman',5.00,'75960608653500211','Iceman and Kitty Pryde must rescue a boy whose mutant powers have just manifested.','2017-08-01',NULL,2,'comics','75960608653500211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Iceman','Iceman',5.00,'75960608653500511','Moments after Iceman comes out to his parents, Juggernaut begins wreaking havoc in Manhattan.','2017-11-01',NULL,5,'comics','75960608653500511.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Purple Daughter','Jessica Jones',42.00,'978130291511751999','NB: This item is in a used condition.','2017-11-02',NULL,1,'comics','978130291511751999.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Kick-Ass','Kick-Ass',3.00,'75960607937700311','What''s a tween girl assassin to do once she''s locked up? Start running all the gangs in the joint, of course! After the surviving the brutal pecking order of middle school, Hit-Girl finds jail just might be a little more up her alley. Meanwhile, Kick-Ass starts learning there''s more to life than just superhero work.','2013-11-01',3,3,'comics','75960607937700311.jpg',5);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Born Against','Kingpin',8.00,'75960608617700111','The KINGPIN has done bad things. Deplorable things. He has cheated the law. He has blackmailed rivals. He has killed. But that''s all in the past. The Kingpin is back in the city that he loves and ready to make his mark as a titan of legitimate industry, but needs to rekindle his public image.','2017-04-01',NULL,1,'comics','75960608617700111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Kickers, Inc.','Kickers, Inc.',1.00,'7148602221308','NB: This item is in a used condition.','1987-08-01',1,10,'comics','7148602221308.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Kickers, Inc.','Kickers, Inc.',1.00,'7148602221312','NB: This item is in a used condition.','1986-12-01',1,2,'comics','7148602221312.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Fallen One, Chapter One','Legend of the Hawkman',5.00,'76194122226400111','NB: This item is in a used condition.','2000-09-01',NULL,1,'comics','76194122226400111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Flight of Faith, Chapter One','Legend of the Hawkman',5.00,'76194122226400311','NB: This item is in a used condition.','2000-11-01',NULL,3,'comics','76194122226400311.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('BIG TROUBLE IN THE BIG EASY!','Luke Cage',3.00,'75960608689400311','Luke Cage and Warhawk battle the super-powered mobster’s son Frankie Corello.','2017-09-01',NULL,3,'comics','75960608689400311.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Ghosts & Miracles','The League of Extraordinary Gentlemen',5.00,'76194121837300211','Miss Murray, Allan Quatermain, and Auguste Dupin capture Mr. Hyde. The group, sans Dupin, returns to England and Murray, Quatermain, and Nemo travel to Miss Coote’s Academy for Wayward Gentlewomen, where they capture Hawler Griffin, the invisible man.','1999-04-01',NULL,2,'comics','76194121837300211.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Mysteries of the East','The League of Extraordinary Gentlemen',5.00,'76194121837300311','Miss Murray and Hawley Griffin visit Quong Lee, from whom they discover that "the waters lap beneath the heavenly bridge. The dragon sleeps below the waters." While looking for Ho Ling, Allan Quatermain and Dr. Jekyll find the Doctor himself. Following Quong Lee’s clue, Miss Murray and Allan Quatermain search the chunnel and find a spectacular air craft.','1999-05-01',NULL,3,'comics','76194121837300311.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Phases of Deimos','The League of Extraordinary Gentlemen',5.00,'76194122728300111','One of the most celebrated series in recent memory makes its triumphant return! The action begins immediately following the events in Volume One. It is 1898, and there are strange rumblings in the sky. Flashing lights dance across the horizon. The Martians are coming…and the Earth will never be the same. Extra bonus feature: A travel guide of fantastic proportions! Presenting a visitors’ guide to some of the world’s strangest places – a magical mystery tour unlike any other!','2002-09-01',2,1,'comics','76194122728300111.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('You Should See Me Dance the Polka','The League of Extraordinary Gentlemen',5.00,'76194122728300611','The grand finale! The last hope of the Empire, nay, the Earth, rests in the hands of our grand adventurers. Prepare to dab your eyes as more than one League member makes the ultimate sacrifice!','2003-11-01',2,6,'comics','76194122728300611.jpg',3);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Magneto','Magneto',9.00,'75960607981001011','When Magneto discovers that mutants are being hauled away to a re-education camp, he goes to investigate… • And when he discovers that the RED SKULL is behind the operation-and in possession of the brain and powers of his deceased ally and friend, Charles Xavier, no less-Magneto becomes determined to shut it down! • But can the Master of Magnetism overcome the Red Skull and his terrifying S-Men?','2014-11-01',NULL,10,'comics','75960607981001011.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Ascendance','Magneto Rex',6.00,'75960604750500111','Magneto arrives in Genosha as its new monarch with a civil war between Magistrates and mutates in full swing. Quicksilver shows up in Genosha to confront his father but is captured by rebel mutates who want to keep their land from Maggie. Rogue joins the party as well.','1999-04-01',1,1,'comics','75960604750500111.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Handle Towards My Hand','Mage',3.00,'70985313001700111','NB: This item is in a used condition.','1997-07-01',NULL,1,'comics','70985313001700111.jpg',6);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('When We Three Shall Meet','Mage',3.00,'70985313001700211','NB: This item is in a used condition.','1997-08-01',NULL,2,'comics','70985313001700211.jpg',6);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('New Mutants','New Mutants',8.00,'75960606838801011','Written by ZEB WELLS Penciled by PAUL DAVIDSON Cover by ADAM KUBERT Special Variant by TBA Why do the New Mutants exist? Why are they a team? Cyclops runs the X-Men as one giant army, not separate squads. So, why do the New Mutants exist as a squad? The answer isn’t what you expect.','2010-04-01',NULL,10,'comics','75960606838801011.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Necrosha: New Mutants, Chapter Three','New Mutants',8.00,'75960606838800811','Dani and Sunspot race to save Magma’s life while Cannonball, Karma and Magik try to rescue Doug from the revived Hellions and Warlock makes his way back to the battlefield.','2010-02-01',NULL,8,'comics','75960606838800811.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Neohedron','New Avengers',8.00,'75960608352700211','Welcome to AVENGERS IDEA MECHANICS – a super-scientific global rescue squad of tomorrow''s heroes… today! America doesn''t want them! S.H.I.E.L.D. doesn''t know what to do with them! But Earth might not survive without… the NEW AVENGERS!','2015-12-01',NULL,2,'comics','75960608352700211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Punisher','The Punisher',3.00,'75960607619200311','Even 10,000 feet above New York, no one escapes the Punisher. As Frank trails the criminal underbelly of the city, he encounters the deadly, mob created villain: THE VULTURE for a brutal battle against death and gravity. Meanwhile as NYPD detectives get closer to understanding Frank Castle''s new relationship, one of New York''s finest is struggling keep his own Punisher association untraceable.','2011-11-01',NULL,3,'comics','75960607619200311.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Kitchen Irish Part Six','The Punisher',3.00,'75960605497801211','The Irish gangs decide to unite, only to be blown up together.','2004-12-01',NULL,12,'comics','75960605497801211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Siege of Wundagore Part 4: Heir of Magneto','Quicksilver',2.00,'75960603877001211','Quicksilver has been captured and the mysterious Nestor shows up and inspires him to use the powers of his father, Magneto, to escape. He snatches Isotope E away from Man-Beast and then leads the Knights of Wundagore and Heroes for Hire against the combined forces of Man-Beast, Exodus and the Acolytes. Using Isotope E to heighten his powers, Quicksilver is able to defeat Exodus and declares himself the true leader of the Acolytes. Unfortunately, the High Evolutionary bursts in to reclaim Wundagore for himself as he swears he is about to take Earth to the next step in its evolution.','1998-10-01',1,12,'comics','75960603877001211.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Red Team','Red Team',3.00,'72513020222200211','The Rules: in which our heroes take a further step down a very dangerous road and lay out their battle plan. But not everyone is happy with the unit’s new direction, especially some of the other players in the game…','1998-10-02',NULL,2,'comics','72513020222200211.jpg',7);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Double Tap, Center Mass','Red Team',3.00,'72513024918003011','Eddie and Trudy start realizing just how deep they''re in, as the extent of Eric Nightingale''s influence becomes clear. Eric has agreed to wear a wire-but will the evidence he gathers help or hinder our heroes'' investigation? And will the complications of their personal lives throw a further spanner in the works?','1998-11-05',NULL,3,'comics','72513024918003011.jpg',7);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Beneath the Skin','Star Trek',9.00,'82771411129300211','The Klingon perspective of the Star Trek: The Original Series episode "The Trouble with Tribbles."','2007-05-01',NULL,2,'comics','82771411129300211.jpg',8);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('The Galactus Seed 5: God of Carnage','The Mighty Thor',5.00,'75960607526300511','The Asgardians continue their fight against Galactus. Volstagg leads the Brigade of Realms to confront Pastor Mike and his congregation. Loki steals the Worldheart/Galactus Seed and jumps into Yggdrasil. Pastor Mike confronts Galactus.','2011-10-01',NULL,5,'comics','75960607526300511.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Fear Itself: In the beginning','The Mighty Thor',9.00,'75960607526300711','After Bor’s death, Cul and his Worthy allow Sleipnir and others to run amok among the mortals. Odin, Vili and Vi oppose them. Odin sacrifices his right eye to Yggdrasil in exchange for wisdom. Cul contains the Worthy in their weapons so he can call upon them in the future. Odin defeats and imprisons Cul. Odin razes Aesheim and renames it Midgard.','2011-12-01',NULL,7,'comics','75960607526300711.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Redpath','Turok',7.00,'71689287065100311','NB: This item is in a used condition.','1997-10-01',1,1,'comics','71689287065100311.jpg',9);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('X-Men: Divided Part One','The Uncanny X-Men',3.00,'75960602461249511','With Xavier dead and the X-Men officially disbanded (or at least that’s what Cyclops tells Iron Man), Scott and Emma spend some down time in the Savage Land. Wolverine, Peter and Kurt visit Germany and then head off into Russia. Angel arrives in San Francisco to find that things have mysteriously reverted back to the groovy sixties.','2008-04-01',NULL,495,'comics','75960602461249511.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Know Thy Enemy','The Uncanny X-Men',5.00,'75960602461233711','Wolverine has a heart to heart talk with Xavier about the latter’s responsibility in the Onslaught debacle that killed many of Earth’s mightiest heroes. The X-Men goof off a little and try to get back to normal.','1996-10-01',1,337,'comics','75960602461233711.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Hive Part 3 of 3','All-New Wolverine',8.50,'75960608359602411','ONE SMALL STEP FOR MAN, ONE GIANT STEP FOR WOLVERINE! • On an alien world in uncharted space, WOLVERINE and the GUARDIANS OF THE GALAXY continue their battle against waves and waves of BROOD! • And with GABBY taken by the Brood colony, Wolverine is going to have to fight tooth and claw to save her little sister. • And what secret about the Kinney Virus does this strange planet hold?','2017-11-01',NULL,24,'comics','75960608359602411.jpg',2);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Will of Iron','Warhammer 40,000',3.00,'07447071032500211','Three superhuman warriors, humanity''s last defence against the horror that stalks the warp… Three perspectives on the eternal battle against Chaos – in an all-new front of the war! Baltus, climbing the ranks of the Dark Angels and discovering shocking revelations at every turn. Interrogator Chaplain Altheous, preserving his chapter''s secrets at all costs. And Inquisitor Sabbathiel and her warband, holding the Dark Angels to account, as heresey gnaws from within!','2016-12-01',NULL,2,'comics','07447071032500211.jpg',10);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Gehenna','Y: The Last Man',3.00,'76194123105104811','The final and most important “secret origin” issue of the series reveals the untold story behind former Israeli Defense Forces leader Alter Tse''elon. What drives this female soldier''s hunt for the last man on Earth, and what will Alter find that could mean the end of Yorick Brown?','2006-10-01',NULL,48,'comics','76194123105104811.jpg',11);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Zombies That Ate The World','Zombies That Ate The World',3.00,'88214200199800201','The entire world must change to confront the emergence of zombie life in this all new edition of a comics masterpiece from DDP and Humanoids!','2016-12-01',NULL,2,'comics','88214200199800201.jpg',12);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Hoard','Hoard',30.00,'799439888210','Hoard is a dynamic game of hand management, set collection, and press-your-luck. Each turn players take one of four possible actions: 1) roll a custom die and move to take a new card, 2) secure a set of treasures or add to an existing set to score points, 3) affect the dragon, who wakes in stages from his tail to his head, by playing cards that soothe or rouse him, or 4) use a sword on an opponent or capture a used sword with a shield. The board is composed of 12 facedown cards surrounding the dragon. It changes as players remove and replace the cards. Dice rolls between 1-5 enable clockwise or counterclockwise movement and the special symbol allows access to all but one of the cards, so it is a game that rewards memory.','1905-07-06',NULL,NULL,'boardgames','799439888210.jpg',13);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Munchkin Deluxe','Munchkin Deluxe',60.00,'837654320976','This award-winning card game, designed by Steve Jackson, captures the essence of the dungeon experience... with none of that stupid roleplaying stuff. You and your friends compete to kill monsters and grab magic items. And what magic items! Don the Horny Helmet and the Boots of Butt-Kicking. Wield the Staff of Napalm... or maybe the Chainsaw of Bloody Dismemberment. Start by slaughtering the Potted Plant and the Drooling Slime, and work your way up to the Plutonium Dragon...','1905-06-23',NULL,NULL,'boardgames','837654320976.jpg',14);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Settlers Of Catan','Settlers Of Catan',99.00,'2987703071204900','In Settlers of Catan, players control a group of settlers exploring and taming the uncharted lands of Catan. Build settlements, roads, and villages by taking commodities from the land around you! This revised edition also includes a game tray designed to hold the 5-6 player extension components.','1905-06-17',NULL,NULL,'boardgames','2987703071204900.jpg',15);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Cards Against Humanity','Cards Against Humanity',65.00,'754207313592','Play begins with a judge, known as the "Card Czar", choosing a black question or fill-in-the-blank card from the top of the deck and showing it to all players. Each player holds a hand of ten white answer cards at the beginning of each round, and passes a card (sometimes two) to the Card Czar, face-down, representing their answer to the question on the card. The card czar determines which answer card(s) are funniest in the context of the question or fill-in-the-blank card. The player who submitted the chosen card(s) is given the question card to represent an "Awesome Point", and then the player to the left of the new Card Czar becomes the new Czar for the next round. Play continues until the players agree to stop, at which point the player with the most Awesome Points is the winner.','1905-07-01',NULL,NULL,'boardgames','754207313592.jpg',1);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Crimeopolis','Crimeopolis',99.00,'750258699708','Set in 1926, you are an unsuccessful gangster in a petty town. Tired of doing small jobs that only earn stress and scars, you dream of putting the hype on big time. The rumble on the street is the big guys in the big cities are pulling the big dough, and you want to be the most prestigious of them all. Crimopolis is a fast-paced strategy board game about bean-shooters, chippies, and sugar in a city where nothing counts but underground influence. Recruit criminals, explore the city, execute illicit jobs, ambush others and take over their assets. Grow your skills and abilities, so you can counteract when reporters and enemies get in the way.','2019-11-29',NULL,NULL,'boardgames','750258699709.jpg',16);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Wingspan','Wingspan',120.00,'644216627721','You are bird enthusiasts—researchers, bird watchers, ornithologists, and collectors—seeking to discover and attract the best birds to your network of wildlife preserves. Each bird extends a chain of powerful combinations in one of your habitats (actions). These habitats focus on several key aspects of growth','1905-07-11',NULL,NULL,'boardgames','644216627721.jpg',17);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Joking Hazard','Joking Hazard',55.00,'859364006087','From the creators of Cyanide & Happiness comes a card game where players compete to finish an awful comic strip.','1905-07-08',NULL,NULL,'boardgames','859364006087.jpg',18);
INSERT INTO products(Title,Series,Price,SKU,Description,Date_of_Publication,Volume,Number,Category,Image,Publisher_FK) VALUES ('Flipology','Flipology',20.00,'793591395098','In Flipology, players try to score the most points over three rounds. At the start of the game, each player receives nine cards, then picks seven of them to arrange in a face-down row. On your turn, you must flip one of your seven cards (up or down), with some cards having effects that enable you to flip additional cards, including those owned by opponents. Cards depict animals in different types of environments, and they have different effects and point values depending on what''s shown at round''s end, such as the sloth which is worth positive points only if it''s still face down. Aside from sloths and koalas, though, cards must end the game face up to contribute to a player''s score.','1905-07-11',NULL,NULL,'boardgames','793591395098.jpg',13);
